browser: chrome
headless: false
environment: qa
device: Desktop Chrome
url: https://example.cypress.io/todo#/
defaultWaitSeconds: 5
#Report related configurations
reportTheme: 'simple'
reportJson: 'src/example/resources/reports/results.json'
reportPath: 'src/example/resources/reports/results.html'
reportTitle: 'Test Summary Report'
reportLaunch: true